# Generated by Django 5.0.6 on 2024-05-18 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_area', models.CharField(max_length=100)),
                ('descripcion_area', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CargoStaff',
            fields=[
                ('id_cstaff', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_cstaff', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Colindancia',
            fields=[
                ('id_colindancia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_colindancia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id_cuota', models.IntegerField(primary_key=True, serialize=False)),
                ('numero_cuotas', models.CharField(max_length=50)),
                ('fecha_vencimiento', models.CharField(max_length=50)),
                ('deuda_total', models.FloatField()),
                ('amortizacion', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Distancia',
            fields=[
                ('id_distancia', models.AutoField(primary_key=True, serialize=False)),
                ('distancia', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id_permisos', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_permiso', models.CharField(max_length=50)),
                ('descripcion_permiso', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tcliente', models.IntegerField()),
                ('nombre_tclliente', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CronogramaPagos',
            fields=[
                ('id_cpagos', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion_cpagos', models.CharField(max_length=255)),
                ('cuota_inicial', models.FloatField()),
                ('cuota_mensual', models.FloatField()),
                ('fecha_inicio_pago', models.CharField(max_length=50)),
                ('plazo_anios', models.CharField(max_length=50)),
                ('plazo_meses', models.CharField(max_length=50)),
                ('TEA', models.FloatField()),
                ('dias_pago', models.CharField(max_length=50)),
                ('descuento', models.FloatField()),
                ('id_cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cuota')),
            ],
        ),
        migrations.CreateModel(
            name='Lado',
            fields=[
                ('id_lado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_lado', models.CharField(max_length=50)),
                ('id_colindancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.colindancia')),
                ('id_distancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.distancia')),
            ],
        ),
        migrations.CreateModel(
            name='Lotes',
            fields=[
                ('id_lote', models.AutoField(primary_key=True, serialize=False)),
                ('numero_lote', models.IntegerField()),
                ('area', models.FloatField()),
                ('ip_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Manzana',
            fields=[
                ('id_manzana', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_manzana', models.CharField(max_length=10)),
                ('id_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lotes')),
            ],
        ),
        migrations.CreateModel(
            name='Perimetro',
            fields=[
                ('id_perimetro', models.AutoField(primary_key=True, serialize=False)),
                ('id_lado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lado')),
            ],
        ),
        migrations.AddField(
            model_name='lotes',
            name='ip_perimetro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.perimetro'),
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proyecto', models.CharField(max_length=100)),
                ('fecha_inicio', models.CharField(max_length=50)),
                ('fecha_fin', models.CharField(max_length=50)),
                ('id_manzana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.manzana')),
            ],
        ),
        migrations.CreateModel(
            name='Persona_Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proyectos')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50)),
                ('id_cstaff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cargostaff')),
                ('id_tcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipocliente')),
            ],
        ),
        migrations.CreateModel(
            name='Lotes_Perimetro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lotes')),
                ('id_perimetro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.perimetro')),
            ],
            options={
                'unique_together': {('id_lote', 'id_perimetro')},
            },
        ),
        migrations.CreateModel(
            name='Permisos_Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.area')),
                ('id_permisos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.permisos')),
            ],
            options={
                'unique_together': {('id_permisos', 'id_area')},
            },
        ),
    ]
