# Generated by Django 5.0.6 on 2024-05-18 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_area_cargostaff_colindancia_cuota_distancia_estado_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persona_Proyectos',
            new_name='Persona_Proyecto',
        ),
        migrations.RenameModel(
            old_name='Proyectos',
            new_name='Proyecto',
        ),
    ]
