# Generated by Django 5.0.6 on 2024-05-18 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_persona_proyectos_persona_proyecto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medio',
            fields=[
                ('id_medio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_medio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Observaciones',
            fields=[
                ('id_observaciones', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion_observaciones', models.CharField(max_length=255)),
                ('adjuntar_informacion', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Lotes',
            new_name='Lote',
        ),
        migrations.RenameModel(
            old_name='Lotes_Perimetro',
            new_name='LotePerimetro',
        ),
        migrations.RenameModel(
            old_name='Permisos',
            new_name='Permiso',
        ),
        migrations.RenameModel(
            old_name='Permisos_Area',
            new_name='PermisoArea',
        ),
        migrations.RenameField(
            model_name='permiso',
            old_name='id_permisos',
            new_name='id_permiso',
        ),
        migrations.RenameField(
            model_name='PermisoArea',
            old_name='id_permisos',
            new_name='id_permiso',
        ),
        migrations.AlterUniqueTogether(
            name='PermisoArea',
            unique_together={('id_permiso', 'id_area')},
        ),
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id_canal', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_canal', models.CharField(max_length=100)),
                ('id_medio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medio')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteCerrado',
            fields=[
                ('id_cliente_cerrado', models.IntegerField(primary_key=True, serialize=False)),
                ('profesion', models.CharField(max_length=100)),
                ('ocupacion', models.CharField(max_length=100)),
                ('centro_trabajo', models.CharField(max_length=255)),
                ('direccion_laboral', models.CharField(max_length=255)),
                ('antiguedad_laboral', models.CharField(max_length=100)),
                ('constancia_inicial', models.CharField(max_length=100)),
                ('id_observaciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.observaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id_origen', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_origen', models.CharField(max_length=100)),
                ('id_canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.canal')),
            ],
        ),
        migrations.RenameModel(
            old_name='Roles',
            new_name='Rol',
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombres_apellidos', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=20)),
                ('dni', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('conyuge', models.BooleanField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=255)),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.area')),
                ('id_cliente_cerrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clientecerrado')),
                ('id_cpagos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cronogramapagos')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rol')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.persona')),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proyecto')),
            ],
            options={
                'unique_together': {('id_persona', 'id_proyecto')},
            },
        ),
        migrations.DeleteModel(
            name='Persona_Proyecto',
        ),
    ]
