# Generated by Django 5.0.6 on 2024-05-18 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_medio_observaciones_rename_lotes_lote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='id_cstaff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.cargostaff'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='id_tcliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tipocliente'),
        ),
    ]
