# Generated by Django 5.0.6 on 2024-05-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_rol_id_cstaff_alter_rol_id_tcliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='id_cstaff',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='id_tcliente',
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre_rol',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='CargoStaff',
        ),
        migrations.DeleteModel(
            name='TipoCliente',
        ),
    ]
