# Generated by Django 5.0.6 on 2024-05-20 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_rol_id_cstaff_remove_rol_id_tcliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manzana',
            name='id_lote',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='id_manzana',
        ),
        migrations.AddField(
            model_name='lote',
            name='ip_manzana',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.manzana'),
        ),
        migrations.AddField(
            model_name='manzana',
            name='id_proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.proyecto'),
        ),
    ]
