# Generated by Django 5.0.6 on 2024-05-20 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_lado_id_colindancia_remove_lado_id_distancia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='colindacia_derecha',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='colindacia_fondo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='colindacia_frente',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='colindacia_izquierda',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='distancia_derecha',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='distancia_fondo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='distancia_frente',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='distancia_izquierda',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='perimetro',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='precio_m2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='ip_estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.estado'),
        ),
    ]
