# Generated by Django 5.0.6 on 2024-05-20 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_lote_colindacia_derecha_lote_colindacia_fondo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='celular',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.area'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id_cliente_cerrado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.clientecerrado'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id_cpagos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.cronogramapagos'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombres_apellidos',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
