# Generated by Django 5.0.6 on 2024-05-20 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_persona_celular_alter_persona_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='id_cliente_cerrado',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='id_cpagos',
        ),
        migrations.AddField(
            model_name='cronogramapagos',
            name='id_cliente_cerrado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.clientecerrado'),
        ),
        migrations.AlterField(
            model_name='clientecerrado',
            name='id_cliente_cerrado',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='observaciones',
            name='id_observaciones',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='persona',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.area'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id_rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.rol'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombres_apellidos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CPagosPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cpagos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cronogramapagos')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.persona')),
            ],
            options={
                'unique_together': {('id_cpagos', 'id_persona')},
            },
        ),
    ]
