# Generated by Django 5.0.6 on 2024-05-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_clientecerrado_id_persona'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personaproyecto',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='area',
            name='id_area',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='canal',
            name='id_canal',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cronogramapagos',
            name='id_cpagos',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='id_cuota',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medio',
            name='id_medio',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='origen',
            name='id_origen',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='id_permiso',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
