# Generated by Django 5.0.6 on 2024-05-20 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_personaproyecto_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='id_proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.proyecto'),
        ),
        migrations.DeleteModel(
            name='PersonaProyecto',
        ),
    ]
