# Generated by Django 5.0.6 on 2024-05-20 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_persona_id_proyecto_delete_personaproyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='id_proyecto',
        ),
        migrations.CreateModel(
            name='PersonaProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.persona')),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='proyectos',
            field=models.ManyToManyField(related_name='personas', through='api.PersonaProyecto', to='api.proyecto'),
        ),
    ]
