# Generated by Django 5.0.6 on 2024-05-20 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_persona_id_proyecto_personaproyecto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaproyecto',
            name='id_lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.lote'),
        ),
    ]
