# Generated by Django 5.0.6 on 2024-05-20 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_personaproyecto_id_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaproyecto',
            name='id_manzana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.manzana'),
        ),
    ]
