# Generated by Django 5.0.6 on 2024-05-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_personaproyecto_id_manzana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='descripcion_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
