# Generated by Django 5.0.6 on 2024-05-21 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_permisoarea_unique_together_area_permisos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='permisos',
        ),
        migrations.RemoveField(
            model_name='permisoarea',
            name='id_permiso',
        ),
        migrations.RemoveField(
            model_name='permisoarea',
            name='id_area',
        ),
        migrations.CreateModel(
            name='RolArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.area')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rol')),
            ],
        ),
        migrations.AddField(
            model_name='rol',
            name='areas',
            field=models.ManyToManyField(related_name='area', through='api.RolArea', to='api.area'),
        ),
        migrations.DeleteModel(
            name='Permiso',
        ),
        migrations.DeleteModel(
            name='PermisoArea',
        ),
    ]
