# Generated by Django 5.0.6 on 2024-05-21 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_area_permisos_remove_permisoarea_id_permiso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronogramapagos',
            name='id_cliente_cerrado',
        ),
        migrations.AlterUniqueTogether(
            name='cpagospersona',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cpagospersona',
            name='id_cpagos',
        ),
        migrations.RemoveField(
            model_name='cpagospersona',
            name='id_persona',
        ),
        migrations.RemoveField(
            model_name='rolarea',
            name='id_area',
        ),
        migrations.RemoveField(
            model_name='rolarea',
            name='id_rol',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='areas',
        ),
        migrations.RemoveField(
            model_name='cronogramapagos',
            name='id_cuota',
        ),
        migrations.AddField(
            model_name='cronogramapagos',
            name='id_persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.persona'),
        ),
        migrations.AddField(
            model_name='cuota',
            name='id_cpagos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.cronogramapagos'),
        ),
        migrations.AddField(
            model_name='observaciones',
            name='id_persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.persona'),
        ),
        migrations.AddField(
            model_name='persona',
            name='antiguedad_laboral',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='centro_trabajo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='constancia_inicial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='direccion_laboral',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='id_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.origen'),
        ),
        migrations.AddField(
            model_name='persona',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='profesion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ClienteCerrado',
        ),
        migrations.DeleteModel(
            name='CPagosPersona',
        ),
        migrations.DeleteModel(
            name='RolArea',
        ),
    ]
