# Generated by Django 5.0.6 on 2024-05-21 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_cronogramapagos_id_cliente_cerrado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canal',
            name='id_medio',
        ),
        migrations.RemoveField(
            model_name='origen',
            name='id_canal',
        ),
        migrations.AddField(
            model_name='canal',
            name='id_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.origen'),
        ),
        migrations.AddField(
            model_name='medio',
            name='id_canal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.canal'),
        ),
    ]
