# Generated by Django 5.0.6 on 2024-05-21 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_canal_id_medio_remove_origen_id_canal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canal',
            name='id_origen',
        ),
        migrations.RemoveField(
            model_name='medio',
            name='id_canal',
        ),
        migrations.AddField(
            model_name='persona',
            name='id_canal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.canal'),
        ),
        migrations.AddField(
            model_name='persona',
            name='id_medio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.medio'),
        ),
    ]
