# Generated by Django 5.0.6 on 2024-05-21 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_canal_id_origen_remove_medio_id_canal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaproyecto',
            name='id_cpagos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.cronogramapagos'),
        ),
    ]
