# Generated by Django 5.0.6 on 2024-05-22 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_persona_fecha_registro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Programmer',
        ),
    ]
