# Generated by Django 5.0.6 on 2024-05-23 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_proyecto_fecha_fin_alter_proyecto_fecha_inicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lote',
            old_name='ip_estado',
            new_name='id_estado',
        ),
        migrations.RenameField(
            model_name='lote',
            old_name='ip_manzana',
            new_name='id_manzana',
        ),
    ]
