# Generated by Django 5.0.6 on 2024-05-23 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_rename_ip_estado_lote_id_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manzana',
            name='id_proyecto',
        ),
    ]
