# Generated by Django 5.0.6 on 2024-05-23 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remove_manzana_id_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='id_manzana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.manzana'),
        ),
    ]
