# Generated by Django 5.0.6 on 2024-05-23 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_proyecto_id_manzana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='id_manzana',
        ),
        migrations.AddField(
            model_name='manzana',
            name='id_lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.lote'),
        ),
    ]
