# Generated by Django 5.0.6 on 2024-05-23 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_lote_id_manzana_manzana_id_lote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manzana',
            name='id_lote',
        ),
        migrations.AddField(
            model_name='lote',
            name='id_manzana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.manzana'),
        ),
    ]
