# Generated by Django 5.0.6 on 2024-05-24 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_manzana_id_lote_lote_id_manzana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='id_manzana',
        ),
        migrations.CreateModel(
            name='ProyectoManzana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_manzana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.manzana')),
                ('id_proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.proyecto')),
            ],
        ),
    ]
