# Generated by Django 5.0.6 on 2024-05-24 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_proyecto_id_manzana_proyectomanzana'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='id_manzana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.manzana'),
        ),
        migrations.DeleteModel(
            name='ProyectoManzana',
        ),
    ]
