# Generated by Django 5.0.6 on 2024-05-27 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_rename_colindacia_fondo_lote_colindancia_fondo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lote',
            old_name='colindacia_derecha',
            new_name='colindancia_derecha',
        ),
        migrations.RenameField(
            model_name='lote',
            old_name='colindacia_frente',
            new_name='colindancia_frente',
        ),
    ]
