# Generated by Django 5.0.6 on 2024-07-02 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_rename_colindacia_derecha_lote_colindancia_derecha_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonaProyecto',
            new_name='FichaDatosCliente',
        ),
    ]
