# Generated by Django 5.0.6 on 2024-07-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_rename_personaproyecto_fichadatoscliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronogramapagos',
            name='cuota_balloon',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cronogramapagos',
            name='cuota_balloon_meses',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
