# Generated by Django 4.2.13 on 2024-08-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_remove_cronogramapagos_id_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
