# Generated by Django 4.2.13 on 2024-08-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_persona_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='nombre_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='correo',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre_rol',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
