# Generated by Django 4.2.13 on 2024-08-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_remove_proyecto_fecha_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
