# Generated by Django 4.2.13 on 2024-08-29 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_proyecto_fecha_inicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lote',
            old_name='id_proyecto',
            new_name='proyecto',
        ),
    ]
