# Generated by Django 4.2.13 on 2024-08-29 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_rename_id_proyecto_lote_proyecto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lote',
            old_name='proyecto',
            new_name='id_proyecto',
        ),
    ]
