# Generated by Django 4.2.13 on 2024-09-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_remove_fichadatoscliente_id_proyecto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cronogramapagos',
            old_name='cuota_balloon',
            new_name='precio_venta_dolares',
        ),
        migrations.RemoveField(
            model_name='cronogramapagos',
            name='cuota_balloon_meses',
        ),
        migrations.AddField(
            model_name='cronogramapagos',
            name='precio_venta_soles',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='precio',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='precio_m2',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
    ]
