# Generated by Django 4.2.13 on 2024-09-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_remove_cuota_id_cpagos_delete_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='direccion',
            new_name='departamento',
        ),
        migrations.AddField(
            model_name='persona',
            name='distrito',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='pais',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='provincia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
