# Generated by Django 4.2.13 on 2024-09-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_rename_direccion_persona_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fecha_creacion',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
    ]
