# Generated by Django 4.2.13 on 2024-09-17 20:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_alter_persona_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
