# Generated by Django 4.2.13 on 2024-09-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_alter_persona_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='conyuge',
            field=models.BooleanField(default=False),
        ),
    ]
