# Generated by Django 4.2.13 on 2024-09-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_alter_persona_conyuge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='direccion_laboral',
        ),
        migrations.AlterField(
            model_name='persona',
            name='pais',
            field=models.CharField(default='PERU', max_length=255),
        ),
    ]
