# Generated by Django 4.2.13 on 2024-09-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_remove_persona_direccion_laboral_alter_persona_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='usuario',
            field=models.BooleanField(default=False),
        ),
    ]
