# Generated by Django 4.2.13 on 2024-09-17 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_persona_password_alter_persona_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadatoscliente',
            name='estado_legal',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fichadatoscliente',
            name='id_persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.persona'),
        ),
    ]
