# Generated by Django 4.2.13 on 2024-09-17 21:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_fichadatoscliente_estado_legal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichadatoscliente',
            name='id',
        ),
        migrations.AddField(
            model_name='fichadatoscliente',
            name='id_fichadc',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
