# Generated by Django 4.2.13 on 2024-09-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_remove_fichadatoscliente_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cronogramapagos',
            old_name='cuota_inicial',
            new_name='cuota_inicial_dolares',
        ),
        migrations.RenameField(
            model_name='cronogramapagos',
            old_name='deuda_total',
            new_name='cuota_inicial_soles',
        ),
        migrations.AddField(
            model_name='cronogramapagos',
            name='deuda_total_dolares',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cronogramapagos',
            name='deuda_total_soles',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cronogramapagos',
            name='TEA',
            field=models.FloatField(default=0),
        ),
    ]
