# Generated by Django 4.2.13 on 2024-09-18 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_rename_cuota_inicial_cronogramapagos_cuota_inicial_dolares_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cronogramapagos',
            old_name='amortizacion',
            new_name='pago_adelantado',
        ),
    ]
