# Generated by Django 4.2.13 on 2024-09-18 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_rename_amortizacion_cronogramapagos_pago_adelantado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id_cuota', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago_cuota', models.DateField(blank=True, null=True)),
                ('pago_adelantado', models.BooleanField(default=False)),
                ('monto_pago_adelantado', models.FloatField(blank=True, null=True)),
                ('monto_cuota', models.IntegerField(blank=True, null=True)),
                ('id_cpagos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.cronogramapagos')),
            ],
        ),
    ]
