# Generated by Django 4.2.13 on 2024-09-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_cuota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='pago_adelantado',
            field=models.BooleanField(default=False),
        ),
    ]
