# Generated by Django 4.2.13 on 2024-09-18 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_alter_cuota_pago_adelantado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronogramapagos',
            name='pago_adelantado',
        ),
    ]
