# Generated by Django 4.2.13 on 2024-09-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_remove_cronogramapagos_pago_adelantado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronogramapagos',
            name='observaciones',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
