# Generated by Django 4.2.13 on 2024-09-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_alter_cronogramapagos_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='monto_cuota',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
