# Generated by Django 4.2.13 on 2024-09-18 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_alter_cuota_monto_cuota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuota',
            name='pago_adelantado',
        ),
    ]
