# Generated by Django 4.2.13 on 2024-09-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_remove_cuota_pago_adelantado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='pago_adelantado',
            field=models.BooleanField(default=False),
        ),
    ]
