# Generated by Django 4.2.13 on 2024-09-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_cuota_pago_adelantado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='estado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuota',
            name='morosidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
