# Generated by Django 4.2.13 on 2024-09-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_cuota_estado_cuota_morosidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
