# Generated by Django 4.2.13 on 2024-09-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_alter_cuota_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lote',
            old_name='precio',
            new_name='precio_dolares',
        ),
        migrations.AddField(
            model_name='lote',
            name='precio_soles',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
    ]
