# Generated by Django 4.2.13 on 2024-09-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_rename_precio_lote_precio_dolares_lote_precio_soles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='colindancia_derecha',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='colindancia_fondo',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='colindancia_frente',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='colindancia_izquierda',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='distancia_derecha',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='distancia_fondo',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='distancia_frente',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='distancia_izquierda',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='perimetro',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
    ]
