# Generated by Django 4.2.13 on 2024-09-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_alter_lote_colindancia_derecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='colindancia_derecha',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='colindancia_fondo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='colindancia_frente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='colindancia_izquierda',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
