# Generated by Django 4.2.13 on 2024-09-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_remove_cuota_estado_alter_cuota_morosidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuota',
            old_name='morosidad',
            new_name='estado',
        ),
        migrations.AddField(
            model_name='cuota',
            name='dias_morosidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
