# Generated by Django 4.2.13 on 2024-09-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_rename_morosidad_cuota_estado_cuota_dias_morosidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='precio_m2_soles',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='precio_soles',
        ),
        migrations.AddField(
            model_name='cronogramapagos',
            name='precio_m2_dolares',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cronogramapagos',
            name='precio_m2_soles',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
    ]
