# Generated by Django 4.2.13 on 2024-09-19 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_remove_lote_precio_m2_soles_remove_lote_precio_soles_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lote',
            old_name='precio_dolares',
            new_name='precio_lote_dolares',
        ),
    ]
