# Generated by Django 4.2.13 on 2024-09-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_rename_precio_dolares_lote_precio_lote_dolares'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronogramapagos',
            name='tipo_cuota_inicial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='genero',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
