# Generated by Django 4.2.13 on 2024-09-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_cronogramapagos_tipo_cuota_inicial_persona_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronogramapagos',
            name='tipo_moneda',
            field=models.CharField(blank=True, default='SOLES', null=True),
        ),
    ]
