# Generated by Django 4.2.13 on 2024-09-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_cronogramapagos_tipo_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='tipo_moneda',
            field=models.CharField(blank=True, default='SOLES', null=True),
        ),
    ]
