# Generated by Django 4.2.13 on 2024-09-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_cuota_tipo_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='estado',
            field=models.BooleanField(),
        ),
    ]
