# Generated by Django 4.2.13 on 2024-09-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_alter_cuota_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
