# Generated by Django 4.2.13 on 2024-10-01 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_alter_cuota_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronogramapagos',
            name='inicial_f1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cronogramapagos',
            name='inicial_f2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cronogramapagos',
            name='inicial_separacion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CuotaInicialFraccionada',
            fields=[
                ('id_cuota_inicial', models.AutoField(primary_key=True, serialize=False)),
                ('monto_inicial', models.FloatField(blank=True, null=True)),
                ('id_cpagos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas_iniciales_fraccionadas', to='api.cronogramapagos')),
            ],
        ),
    ]
