# Generated by Django 4.2.13 on 2024-10-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_cronogramapagos_inicial_f1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='nombre_usuario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
