# Generated by Django 4.2.13 on 2024-10-03 16:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_persona_nombre_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('ruc', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonaClient',
            fields=[
                ('id_persona_client', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(blank=True, max_length=255, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=255, null=True)),
                ('genero', models.CharField(blank=True, max_length=255, null=True)),
                ('celular', models.CharField(blank=True, max_length=9, null=True)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(default='PERU', max_length=255)),
                ('departamento', models.CharField(blank=True, max_length=255, null=True)),
                ('provincia', models.CharField(blank=True, max_length=255, null=True)),
                ('distrito', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now)),
                ('ocupacion', models.CharField(blank=True, max_length=100, null=True)),
                ('centro_trabajo', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_documento', models.CharField(blank=True, max_length=255, null=True)),
                ('num_documento', models.CharField(blank=True, max_length=255, null=True)),
                ('conyuge', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='fichadatoscliente',
            name='id_persona',
        ),
        migrations.CreateModel(
            name='PersonaStaff',
            fields=[
                ('id_persona_staff', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(blank=True, max_length=255, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('dni', models.CharField(blank=True, max_length=8, null=True)),
                ('conyuge', models.BooleanField(default=False)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True)),
                ('celular', models.CharField(blank=True, max_length=9, null=True)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('id_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePersona',
            fields=[
                ('id_detalle_persona', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.BooleanField(default=False)),
                ('canal', models.CharField(blank=True, max_length=255, null=True)),
                ('medio', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('origen', models.CharField(blank=True, max_length=255, null=True)),
                ('id_fichadc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fichadatoscliente')),
                ('id_persona_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.personaclient')),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='id_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.empresa'),
        ),
        migrations.AlterField(
            model_name='observaciones',
            name='id_persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.personaclient'),
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
