# Generated by Django 4.2.13 on 2024-10-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='personastaff',
            name='rol',
            field=models.CharField(blank=True, null=True),
        ),
    ]
