# Generated by Django 4.2.13 on 2024-10-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_personastaff_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='ruc',
            field=models.CharField(blank=True, null=True),
        ),
    ]
