# Generated by Django 4.2.13 on 2024-10-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_alter_empresa_ruc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observaciones',
            old_name='id_persona',
            new_name='id_persona_client',
        ),
        migrations.AddField(
            model_name='fichadatoscliente',
            name='asesor',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichadatoscliente',
            name='cod_boleta',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichadatoscliente',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichadatoscliente',
            name='fecha_separacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaclient',
            name='telefono_fijo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
