# Generated by Django 4.2.13 on 2024-10-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_alter_passwordresettoken_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadatoscliente',
            name='fecha_limite_separacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
