# Generated by Django 4.2.13 on 2024-10-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_personastaff_foto_proyecto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='personastaff',
            name='centro_costos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
