# Generated by Django 4.2.13 on 2024-10-18 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_personastaff_centro_costos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobantePago',
            fields=[
                ('id_comprobante_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, null=True)),
                ('codigo', models.CharField(blank=True, null=True)),
                ('monto_cuota', models.FloatField(blank=True, null=True)),
                ('imagen_comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes_pago/')),
                ('monto_cuota_pagado', models.FloatField(blank=True, null=True)),
                ('moneda_pago', models.CharField(blank=True, default='SOLES', null=True)),
                ('id_cuota', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.cuota')),
            ],
        ),
    ]
