# Generated by Django 4.2.13 on 2024-10-18 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_comprobantepago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuota',
            name='monto_pago_adelantado',
        ),
        migrations.RemoveField(
            model_name='cuota',
            name='pago_adelantado',
        ),
    ]
